export interface StorageClient {
  /**
   * Uploads a binary file directly to a storage provider (such as S3 or MinIO)
   * using a presigned URL.
   * 
   * @param file The binary file to upload
   * @param uploadUrl The presigned URL generated by the backend
   * @param headers Optional additional headers
   * @throws Error if the upload fails
   */
  uploadFile(file: File, uploadUrl: string, headers?: Record<string, string>): Promise<void>;
}

export const storageClient: StorageClient = {
  async uploadFile(file: File, uploadUrl: string, headers?: Record<string, string>): Promise<void> {
    const response = await fetch(uploadUrl, {
      method: "PUT",
      body: file,
      headers: {
        "Content-Type": file.type,
        ...headers,
      },
    });

    if (!response.ok) {
      throw new Error(`Error uploading file to storage: ${response.status} ${response.statusText}`);
    }
  },
};
