services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-loresuelvo}/loresuelvo-webapp:${IMAGE_TAG:-main}
    container_name: loresuelvo-webapp-prod
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    restart: unless-stopped
