name: CI Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build y Verificar
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter y Pruebas
        run: |
          npm run lint
          npm test

      - name: Construir Next.js
        run: npm run build

      - name: Construir la imagen de producción
        run: docker build -t loresuelvo-webapp-ci .
