name: Release & Deploy

on:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  run-test:
    uses: ./.github/workflows/ci.yml

  build-and-push:
    needs: run-test
    uses: ./.github/workflows/packaging.yml

  deploy:
    needs: build-and-push
    uses: LoResuelvo/infra-devops/.github/workflows/deploy-webapp.yml@main
    with:
      image-ref: ${{ needs.build-and-push.outputs.image-ref }}
      release-tag: ${{ github.ref_name }}
